// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.24.4
// source: gossip_data.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 원본 블록 데이터
type CurieBlock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DummyData []byte `protobuf:"bytes,1,opt,name=dummy_data,json=dummyData,proto3" json:"dummy_data,omitempty"`
}

func (x *CurieBlock) Reset() {
	*x = CurieBlock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gossip_data_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CurieBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurieBlock) ProtoMessage() {}

func (x *CurieBlock) ProtoReflect() protoreflect.Message {
	mi := &file_gossip_data_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurieBlock.ProtoReflect.Descriptor instead.
func (*CurieBlock) Descriptor() ([]byte, []int) {
	return file_gossip_data_proto_rawDescGZIP(), []int{0}
}

func (x *CurieBlock) GetDummyData() []byte {
	if x != nil {
		return x.DummyData
	}
	return nil
}

// ECDSA Signature
type Signature struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SigR []byte `protobuf:"bytes,1,opt,name=sig_r,json=sigR,proto3" json:"sig_r,omitempty"`
	SigS []byte `protobuf:"bytes,2,opt,name=sig_s,json=sigS,proto3" json:"sig_s,omitempty"`
}

func (x *Signature) Reset() {
	*x = Signature{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gossip_data_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Signature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signature) ProtoMessage() {}

func (x *Signature) ProtoReflect() protoreflect.Message {
	mi := &file_gossip_data_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signature.ProtoReflect.Descriptor instead.
func (*Signature) Descriptor() ([]byte, []int) {
	return file_gossip_data_proto_rawDescGZIP(), []int{1}
}

func (x *Signature) GetSigR() []byte {
	if x != nil {
		return x.SigR
	}
	return nil
}

func (x *Signature) GetSigS() []byte {
	if x != nil {
		return x.SigS
	}
	return nil
}

// 원본 블록 가십 데이터
// 1. 서명된 블록 데이터 Gossip
// 2. 원본 블록의 Hash Value Gossip
type SignedCurieBlockForOG struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body      *CurieBlock `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	Signature *Signature  `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *SignedCurieBlockForOG) Reset() {
	*x = SignedCurieBlockForOG{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gossip_data_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignedCurieBlockForOG) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedCurieBlockForOG) ProtoMessage() {}

func (x *SignedCurieBlockForOG) ProtoReflect() protoreflect.Message {
	mi := &file_gossip_data_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedCurieBlockForOG.ProtoReflect.Descriptor instead.
func (*SignedCurieBlockForOG) Descriptor() ([]byte, []int) {
	return file_gossip_data_proto_rawDescGZIP(), []int{2}
}

func (x *SignedCurieBlockForOG) GetBody() *CurieBlock {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *SignedCurieBlockForOG) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

// 새로운 가십을 위한 암호화된 Hash Value
// 1. 암호화된 블록 Hash Value
type SignedCurieBlockForNG struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Signature *Signature `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *SignedCurieBlockForNG) Reset() {
	*x = SignedCurieBlockForNG{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gossip_data_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignedCurieBlockForNG) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedCurieBlockForNG) ProtoMessage() {}

func (x *SignedCurieBlockForNG) ProtoReflect() protoreflect.Message {
	mi := &file_gossip_data_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedCurieBlockForNG.ProtoReflect.Descriptor instead.
func (*SignedCurieBlockForNG) Descriptor() ([]byte, []int) {
	return file_gossip_data_proto_rawDescGZIP(), []int{3}
}

func (x *SignedCurieBlockForNG) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

var File_gossip_data_proto protoreflect.FileDescriptor

var file_gossip_data_proto_rawDesc = []byte{
	0x0a, 0x11, 0x67, 0x6f, 0x73, 0x73, 0x69, 0x70, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x63, 0x75, 0x72, 0x69, 0x65, 0x22, 0x2b, 0x0a, 0x0a, 0x43, 0x75,
	0x72, 0x69, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x1d, 0x0a, 0x0a, 0x64, 0x75, 0x6d, 0x6d,
	0x79, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x64, 0x75,
	0x6d, 0x6d, 0x79, 0x44, 0x61, 0x74, 0x61, 0x22, 0x35, 0x0a, 0x09, 0x53, 0x69, 0x67, 0x6e, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x12, 0x13, 0x0a, 0x05, 0x73, 0x69, 0x67, 0x5f, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x73, 0x69, 0x67, 0x52, 0x12, 0x13, 0x0a, 0x05, 0x73, 0x69, 0x67,
	0x5f, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x73, 0x69, 0x67, 0x53, 0x22, 0x6e,
	0x0a, 0x15, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x43, 0x75, 0x72, 0x69, 0x65, 0x42, 0x6c, 0x6f,
	0x63, 0x6b, 0x46, 0x6f, 0x72, 0x4f, 0x47, 0x12, 0x25, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x63, 0x75, 0x72, 0x69, 0x65, 0x2e, 0x43, 0x75,
	0x72, 0x69, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x2e,
	0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x63, 0x75, 0x72, 0x69, 0x65, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0x47,
	0x0a, 0x15, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x43, 0x75, 0x72, 0x69, 0x65, 0x42, 0x6c, 0x6f,
	0x63, 0x6b, 0x46, 0x6f, 0x72, 0x4e, 0x47, 0x12, 0x2e, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63, 0x75, 0x72,
	0x69, 0x65, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52, 0x09, 0x73, 0x69,
	0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x42, 0x14, 0x5a, 0x12, 0x66, 0x6c, 0x61, 0x67, 0x2d,
	0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gossip_data_proto_rawDescOnce sync.Once
	file_gossip_data_proto_rawDescData = file_gossip_data_proto_rawDesc
)

func file_gossip_data_proto_rawDescGZIP() []byte {
	file_gossip_data_proto_rawDescOnce.Do(func() {
		file_gossip_data_proto_rawDescData = protoimpl.X.CompressGZIP(file_gossip_data_proto_rawDescData)
	})
	return file_gossip_data_proto_rawDescData
}

var file_gossip_data_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_gossip_data_proto_goTypes = []interface{}{
	(*CurieBlock)(nil),            // 0: curie.CurieBlock
	(*Signature)(nil),             // 1: curie.Signature
	(*SignedCurieBlockForOG)(nil), // 2: curie.SignedCurieBlockForOG
	(*SignedCurieBlockForNG)(nil), // 3: curie.SignedCurieBlockForNG
}
var file_gossip_data_proto_depIdxs = []int32{
	0, // 0: curie.SignedCurieBlockForOG.body:type_name -> curie.CurieBlock
	1, // 1: curie.SignedCurieBlockForOG.signature:type_name -> curie.Signature
	1, // 2: curie.SignedCurieBlockForNG.signature:type_name -> curie.Signature
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_gossip_data_proto_init() }
func file_gossip_data_proto_init() {
	if File_gossip_data_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gossip_data_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CurieBlock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gossip_data_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Signature); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gossip_data_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignedCurieBlockForOG); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gossip_data_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignedCurieBlockForNG); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gossip_data_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gossip_data_proto_goTypes,
		DependencyIndexes: file_gossip_data_proto_depIdxs,
		MessageInfos:      file_gossip_data_proto_msgTypes,
	}.Build()
	File_gossip_data_proto = out.File
	file_gossip_data_proto_rawDesc = nil
	file_gossip_data_proto_goTypes = nil
	file_gossip_data_proto_depIdxs = nil
}
